<x-filament-panels::page>
<div class="font-sans antialiased bg-gray-100">
    <div class="container p-6 mx-auto mt-10 bg-white rounded-lg shadow-lg">
        <!-- Header Section -->
        <div class="flex items-center justify-between mb-6">
            <div>
                <h1 class="text-3xl font-bold text-gray-800">Invoice</h1>
                <p class="text-lg text-gray-600">Invoice #12345</p>
            </div>
            <div class="text-right">
                <p class="text-lg font-semibold text-gray-800">Date: {{ now()->format('F j, Y') }}</p>
            </div>
        </div>

        <!-- From and To Section -->
        <div class="flex justify-between mb-8">
            <div>
                <h3 class="text-xl font-semibold text-gray-800">From</h3>
                <p class="text-gray-600">Your Company Name</p>
                <p class="text-gray-600">123 Main St</p>
                <p class="text-gray-600">City, State, ZIP</p>
                <p class="text-gray-600">Email: info@yourcompany.com</p>
            </div>
            <div class="text-right">
                <h3 class="text-xl font-semibold text-gray-800">To</h3>
                <p class="text-gray-600">Customer Name</p>
                <p class="text-gray-600">456 Another St</p>
                <p class="text-gray-600">City, State, ZIP</p>
                <p class="text-gray-600">Email: customer@example.com</p>
            </div>
        </div>

        <!-- Table for Items -->
        <table class="w-full mb-6 border border-collapse border-gray-300 table-auto">
            <thead>
                <tr class="text-gray-700 bg-gray-200">
                    <th class="px-4 py-2 border-b">Item</th>
                    <th class="px-4 py-2 text-right border-b">Quantity</th>
                    <th class="px-4 py-2 text-right border-b">Unit Price</th>
                    <th class="px-4 py-2 text-right border-b">Total</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td class="px-4 py-2 border-b">Web Design</td>
                    <td class="px-4 py-2 text-right border-b">1</td>
                    <td class="px-4 py-2 text-right border-b">$500.00</td>
                    <td class="px-4 py-2 text-right border-b">$500.00</td>
                </tr>
                <tr>
                    <td class="px-4 py-2 border-b">Development</td>
                    <td class="px-4 py-2 text-right border-b">10</td>
                    <td class="px-4 py-2 text-right border-b">$30.00</td>
                    <td class="px-4 py-2 text-right border-b">$300.00</td>
                </tr>
                <tr>
                    <td class="px-4 py-2 border-b">SEO Services</td>
                    <td class="px-4 py-2 text-right border-b">5</td>
                    <td class="px-4 py-2 text-right border-b">$80.00</td>
                    <td class="px-4 py-2 text-right border-b">$400.00</td>
                </tr>
            </tbody>
            <tfoot>
                <tr>
                    <td class="px-4 py-2" colspan="3" class="font-semibold text-right">Subtotal</td>
                    <td class="px-4 py-2 text-right">$1200.00</td>
                </tr>
                <tr>
                    <td class="px-4 py-2" colspan="3" class="font-semibold text-right">Tax (5%)</td>
                    <td class="px-4 py-2 text-right">$60.00</td>
                </tr>
                <tr class="bg-gray-200">
                    <td class="px-4 py-2" colspan="3" class="font-semibold text-right">Total</td>
                    <td class="px-4 py-2 text-lg font-semibold text-right">$1260.00</td>
                </tr>
            </tfoot>
        </table>

        <!-- Notes Section -->
        <div class="mb-6 text-sm text-gray-600">
            <h3 class="font-semibold text-gray-800">Notes:</h3>
            <p class="mt-2">Thank you for doing business with us! Payment is due within 30 days from the date of this invoice. Please contact us if you have any questions.</p>
        </div>

        <!-- Footer Section -->
        <div class="flex items-center justify-between">
            <div class="text-sm text-gray-600">
                <p>&copy; {{ now()->year }} Your Company. All rights reserved.</p>
            </div>
            <div class="text-right">
                <p class="text-gray-600">Invoice generated by YourCompany</p>
            </div>
        </div>
    </div>
</div>

</x-filament-panels::page>
